# Generated by Django 5.1.7 on 2025-10-31 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_students_last_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("reason", models.TextField(default="", verbose_name="拉黑原因")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.students",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "黑名单管理",
                "db_table": "blacklist",
            },
        ),
        migrations.CreateModel(
            name="ComplaintFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "admin_user",
                    models.CharField(default="", max_length=50, verbose_name="处理管理员"),
                ),
                ("feedback_content", models.TextField(default="", verbose_name="反馈内容")),
                (
                    "feedback_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="反馈时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
            ],
            options={
                "verbose_name_plural": "投诉反馈信息",
                "db_table": "complaint_feedback",
            },
        ),
        migrations.CreateModel(
            name="UserComplaint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("facility", "设施问题"),
                            ("service", "服务问题"),
                            ("environment", "环境问题"),
                            ("other", "其他问题"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="投诉类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="投诉标题"),
                ),
                ("content", models.TextField(default="", verbose_name="投诉内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="投诉时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.students",
                        verbose_name="投诉学生",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "用户投诉管理",
                "db_table": "user_complaint",
            },
        ),
        migrations.CreateModel(
            name="UserEvaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1星"), (2, "2星"), (3, "3星"), (4, "4星"), (5, "5星")],
                        default=5,
                        verbose_name="评分",
                    ),
                ),
                ("comment", models.TextField(default="", verbose_name="评价内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="评价时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.rooms",
                        verbose_name="自习室",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.students",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "用户评价管理",
                "db_table": "user_evaluation",
            },
        ),
        migrations.DeleteModel(
            name="Text",
        ),
        migrations.AddField(
            model_name="complaintfeedback",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="login.usercomplaint",
                verbose_name="投诉记录",
            ),
        ),
    ]
