# Generated by Django 5.1.7 on 2025-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_blacklist_complaintfeedback_usercomplaint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevaluation",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="审核状态"),
        ),
    ]
