# Generated by Django 5.1.7 on 2025-11-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_userevaluation_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="bio",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="个人简介"
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="preferred_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="login.rooms",
                verbose_name="常用自习室",
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="study_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quiet", "安静学习"),
                    ("group", "小组讨论"),
                    ("flexible", "灵活适应"),
                    ("other", "其他"),
                ],
                default="quiet",
                max_length=50,
                verbose_name="学习偏好",
            ),
        ),
    ]
