# Generated by Django 5.1.7 on 2025-11-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_students_bio_students_preferred_room_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistRemovalRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("appeal_reason", models.TextField(verbose_name="申诉理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                ("admin_comment", models.TextField(blank=True, verbose_name="管理员备注")),
                (
                    "blacklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.blacklist",
                        verbose_name="黑名单记录",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.students",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "黑名单撤销申请",
                "db_table": "blacklist_removal_request",
            },
        ),
    ]
