# Generated by Django 5.1.7 on 2025-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0007_blacklistremovalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="booking_date",
            field=models.DateField(blank=True, null=True, verbose_name="预约日期"),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="period",
            field=models.IntegerField(
                choices=[(1, "上午"), (2, "下午"), (3, "晚自习")],
                default=1,
                verbose_name="时间段",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="预约时间"),
        ),
    ]
