# Generated by Django 5.1.7 on 2025-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_backgroundmusic"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundmusic",
            name="artist",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="艺术家"
            ),
        ),
        migrations.AddField(
            model_name="backgroundmusic",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="music/covers/", verbose_name="封面图片"
            ),
        ),
        migrations.AddField(
            model_name="backgroundmusic",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="时长"),
        ),
    ]
